### ISSUE TITLE
Use log or credentials to track versions in S3

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-Tools#1]
Depends on how we can use credentials for Update S3 bucket tool

**Comment by HansVraga** [comment]
Assigning to SysOps as we should consult @aaronstephenson on the best path forward for logging the 'who' and the 'when' for S3 uploads. Going to try to capture the question below:

We're building a tool that allows our StreamStats GIS team (4 dispersed USGS staff) to copy their local StreamStats data (by state) to S3. We have a need to capture who runs this tool each time, and when, so if something breaks we know who to follow up with. S3 will capture the credentials of who last wrote to the bucket - so we could grant each of the SS GIS members S3 credentials and have them enter them whenever they run this tool; or we could attempt to capture this information in a different way (does S3 allow for any meta-data as part of a file upload/update?) - perhaps as a log file within S3 - and use an application-specific set of credentials for S3. 

@aaronstephenson please advise - clarification can be provided if needed.

**Comment by marsmith** [comment]
I think we may have thrown around the idea of a single login with a seperate log file that the scripts would write that would identify users.   but would leave up to aaron

**Comment by aaronstephenson** [comment]
There are many options available to us.

1. [S3 Server Access Logging](https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerLogs.html)
- records every access event (all GETs, POSTs, PUTs, DELETEs, etc), analogous to a web server log, e.g. Apache or IIS

2. [CloudTrail Data Event Logging](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/logging-management-and-data-events-with-cloudtrail.html?icmpid=docs_cloudtrail_console#logging-data-events)
- similar to Server Log, but in CloudTrail format for easy use in other AWS services for things like monitoring alerting; also can be dedicated to recording _only_ reads _or_ writes or both

(both of the above will record the "requester" if the requester is an IAM user)

3. [S3 User-Defined Metadata](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#UserMetadata)
- analogous to file metadata on a file server
- we could add our own metadata key-value pair to record the user

4. [S3 Tagging](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-tagging.html)
- tags are used for categorization but can be used by other AWS services for filtering (like IAM permissions)
- we could add our own tag to record the user (this would require careful use by the client to always include existing tags on existing objects because tags are completely overwritten on each request)

**My Recommendation**: 1 and 3 (with each user given their own IAM account, if the number of users is small). Or possibly all 4, but that could be a lot of work and we should discuss it thoroughly first.

You will probably want to also do your own client-side logging as part of your script to record more granular information, to identify exactly where something went wrong.

**Comment by aaronstephenson** [comment]
We can also enable file versioning on the bucket so nothing ever gets lost, and files can be rolled back if necessary.

**Comment by HansVraga** [comment]
We've implemented logging as part of the script, so right now I'm thinking that enabling versioning in S3 and your 1) option above will cover what we really need @aaronstephenson . 

Still ironing out some testing, but we should probably touch base with you just to give a quick walk-through on what is being done and see if you concur that is all we'll really need.

**Comment by aaronstephenson** [comment]
I have enabled both versioning and Server Access Logging (the logs are being stored in the bucket named 'logging-streamstats-staged-data', to which @jknewson and @marsmith have power user access).

**Comment by HansVraga** [comment]
Same as #10 and #11 - @kjacobsen16 please close if this is complete!

**Comment by kjacobsen16** [comment]
done
